export const pointsData = [
    {
        s_no : '1',
        team_name : 'GT',
        team_logo :'https://scores.iplt20.com/ipl/teamlogos/GT.png?v=1',
        points :'20',
        played : '14',
        won : '10',
        nrr : '0.809',
    },
    {
        s_no : '2',
        team_name : 'CSK',
        team_logo :'https://scores.iplt20.com/ipl/teamlogos/CSK.png',
        points :'17',
        played : '14',
        won : '8',
        nrr : '0.652',
    },  
    {
        s_no : '3',
        team_name : 'LSR',
        team_logo :'https://feeds-100mb.s3-ap-southeast-1.amazonaws.com/teamLogos/ADAMetmKk61682948573LSG.png',
        points :'17',
        played : '14',
        won : '8',
        nrr : '0.284',
    },
    {
        s_no : '4',
        team_name : 'MI',
        team_logo :'https://scores.iplt20.com/ipl/teamlogos/MI.png',
        points :'16',
        played : '14',
        won : '8',
        nrr : '-0.044',
    },
    {
        s_no : '5',
        team_name : 'RR',
        team_logo :'https://scores.iplt20.com/ipl/teamlogos/RR.png',
        points :'14',
        played : '14',
        won : '8',
        nrr : '0.148',
    }, 
    {
        s_no : '6',
        team_name : 'RCB',
        team_logo :'https://scores.iplt20.com/ipl/teamlogos/RCB.png',
        points :'14',
        played : '14',
        won : '7',
        nrr : '0.135',
    }, 
    {
        s_no : '7',
        team_name : 'KKR',
        team_logo :'https://scores.iplt20.com/ipl/teamlogos/KKR.png',
        points :'12',
        played : '14',
        won : '6',
        nrr : '-0.239',
    },
    {
        s_no : '8',
        team_name : 'PBKS',
        team_logo :'https://scores.iplt20.com/ipl/teamlogos/PBKS.png',
        points :'12',
        played : '14',
        won : '6',
        nrr : '-0.304',
    },
    {
        s_no : '9',
        team_name : 'DC',
        team_logo :'https://scores.iplt20.com/ipl/teamlogos/DC.png',
        points :'10',
        played : '14',
        won : '5',
        nrr : '-0.808',
    },
    {
        s_no : '10',
        team_name : 'SRH',
        team_logo :'https://scores.iplt20.com/ipl/teamlogos/SRH.png',
        points :'8',
        played : '14',
        won : '4',
        nrr : '-0.590',
    },
] 