export const tableData = [
    {
        "POS": 1,
        "TEAM": "MI",
        "P": 10,
        "W": 8,
        "L": 1,
        "NR": 1,
        "NRR": 0.75,
        "FOR": 2000,
        "AGAINST": 1800,
        "PTS": 17,
        "RECENT_FORM": "W-W-W-W-L"
      },
      {
        "POS": 2,
        "TEAM": "DC",
        "P": 9,
        "W": 7,
        "L": 2,
        "NR": 0,
        "NRR": 0.50,
        "FOR": 1800,
        "AGAINST": 1500,
        "PTS": 14,
        "RECENT_FORM": "W-W-L-W-W"
      },
      {
        "POS": 3,
        "TEAM": "CSK",
        "P": 10,
        "W": 6,
        "L": 3,
        "NR": 1,
        "NRR": 0.25,
        "FOR": 1700,
        "AGAINST": 1600,
        "PTS": 13,
        "RECENT_FORM": "L-W-W-L-W"
      },
      {
        "POS": 4,
        "TEAM": "KKR",
        "P": 9,
        "W": 5,
        "L": 4,
        "NR": 0,
        "NRR": 0.10,
        "FOR": 1500,
        "AGAINST": 1400,
        "PTS": 10,
        "RECENT_FORM": "W-L-L-W-W"
      },
      {
        "POS": 5,
        "TEAM": "RCB",
        "P": 10,
        "W": 4,
        "L": 5,
        "NR": 1,
        "NRR": -0.20,
        "FOR": 1400,
        "AGAINST": 1500,
        "PTS": 9,
        "RECENT_FORM": "L-L-W-L-W"
      },
      {
        "POS": 6,
        "TEAM": "RR",
        "P": 9,
        "W": 3,
        "L": 6,
        "NR": 0,
        "NRR": -0.50,
        "FOR": 1300,
        "AGAINST": 1600,
        "PTS": 6,
        "RECENT_FORM": "W-L-L-W-L"
      },
      {
        "POS": 7,
        "TEAM": "SRH",
        "P": 10,
        "W": 3,
        "L": 7,
        "NR": 0,
        "NRR": -0.75,
        "FOR": 1200,
        "AGAINST": 1700,
        "PTS": 6,
        "RECENT_FORM": "L-L-W-L-L"
      },
      {
        "POS": 8,
        "TEAM": "PBKS",
        "P": 10,
        "W": 2,
        "L": 8,
        "NR": 0,
        "NRR": -0.90,
        "FOR": 1100,
        "AGAINST": 1900,
        "PTS": 4,
        "RECENT_FORM": "L-L-W-L-L"
      }
]

export const playerData = [
  
  {
                    "POS": "1",
                    "Player": "John",
                    "Mat": 10,
                    "Inns": 9,
                    "NO": 2,
                    "Runs": 350,
                    "HS": 85,
                    "Avg": 43.75,
                    "BF": 280,
                    "SR": 125.00,
                    "Century": 0,
                    "Fifty": 3,
                    "Fours": 40,
                    "Sixes": 5
                },
                {
                    "POS": "2",
                    "Player": "Mike",
                    "Mat": 9,
                    "Inns": 9,
                    "NO": 1,
                    "Runs": 420,
                    "HS": 110,
                    "Avg": 52.50,
                    "BF": 320,
                    "SR": 131.25,
                    "Century": 1,
                    "Fifty": 2,
                    "Fours": 45,
                    "Sixes": 8
                },
                {
                    "POS": "3",
                    "Player": "Sarah",
                    "Mat": 8,
                    "Inns": 8,
                    "NO": 0,
                    "Runs": 280,
                    "HS": 92,
                    "Avg": 35.00,
                    "BF": 210,
                    "SR": 133.33,
                    "Century": 0,
                    "Fifty": 2,
                    "Fours": 30,
                    "Sixes": 3
                },
                {
                    "POS": "4",
                    "Player": "David",
                    "Mat": 10,
                    "Inns": 9,
                    "NO": 1,
                    "Runs": 410,
                    "HS": 78,
                    "Avg": 51.25,
                    "BF": 300,
                    "SR": 136.67,
                    "Century": 0,
                    "Fifty": 4,
                    "Fours": 35,
                    "Sixes": 7
                },
                {
                    "POS": "5",
                    "Player": "Emily",
                    "Mat": 10,
                    "Inns": 10,
                    "NO": 3,
                    "Runs": 280,
                    "HS": 65,
                    "Avg": 35.00,
                    "BF": 200,
                    "SR": 140.00,
                    "Century": 0,
                    "Fifty": 1,
                    "Fours": 20,
                    "Sixes": 2
                },
                {
                    "POS": "6",
                    "Player": "Alex",
                    "Mat": 9,
                    "Inns": 8,
                    "NO": 0,
                    "Runs": 320,
                    "HS": 98,
                    "Avg": 40.00,
                    "BF": 250,
                    "SR": 128.00,
                    "Century": 0,
                    "Fifty": 3,
                    "Fours": 32,
                    "Sixes": 4
                },
                {
                    "POS": "7",
                    "Player": "Sophia",
                    "Mat": 8,
                    "Inns": 7,
                    "NO": 0,
                    "Runs": 220,
                    "HS": 75,
                    "Avg": 31.43,
                    "BF": 180,
                    "SR": 122.22,
                    "Century": 0,
                    "Fifty": 1,
                    "Fours": 25,
                    "Sixes": 1
                },
                {
                    "POS": "8",
                    "Player": "Daniel",
                    "Mat": 10,
                    "Inns": 9,
                    "NO": 2,
                    "Runs": 390,
                    "HS": 80,
                    "Avg": 48.75,
                    "BF": 270,
                    "SR": 144.44,
                    "Century": 0,
                    "Fifty": 3,
                    "Fours": 37,
                    "Sixes": 6
                },
                {
                    "POS": "9",
                    "Player": "Olivia",
                    "Mat": 9,
                    "Inns": 8,
                    "NO": 1,
                    "Runs": 370,
                    "HS": 95,
                    "Avg": 53.57,
                    "BF": 290,
                    "SR": 127.59,
                    "Century": 0,
                    "Fifty": 2,
                    "Fours": 42,
                    "Sixes": 3
                },
                {
                    "POS": "10",
                    "Player": "Matthew",
                    "Mat": 10,
                    "Inns": 9,
                    "NO": 0,
                    "Runs": 440,
                    "HS": 120,
                    "Avg": 55.00,
                    "BF": 330,
                    "SR": 133.33,
                    "Century": 1,
                    "Fifty": 3,
                    "Fours": 50,
                    "Sixes": 10
                }
]